// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz1pEt7Q4ZPWmecXBOlqpdarf-I8GPv5U',
    appId: '1:804667018998:web:eff195d1c0a774b82226d7',
    messagingSenderId: '804667018998',
    projectId: 'khidma-2d423',
    authDomain: 'khidma-2d423.firebaseapp.com',
    storageBucket: 'khidma-2d423.firebasestorage.app',
    measurementId: 'G-YJ3JL3KDGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtMEfEpHWFhYr822fdZnEPRASab5zN4ns',
    appId: '1:804667018998:android:3a3b577b605acc342226d7',
    messagingSenderId: '804667018998',
    projectId: 'khidma-2d423',
    storageBucket: 'khidma-2d423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdJoFL-pc0Ka9dPhNuafkJzJEGSxCWO4',
    appId: '1:804667018998:ios:c517d75f22464b532226d7',
    messagingSenderId: '804667018998',
    projectId: 'khidma-2d423',
    storageBucket: 'khidma-2d423.firebasestorage.app',
    androidClientId: '804667018998-t3hrfdbepig7suftnqoqvqre6rs5uh0a.apps.googleusercontent.com',
    iosClientId: '804667018998-qh21lt7qgoljioiscf7eij7l7bum5kqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.khedma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPdJoFL-pc0Ka9dPhNuafkJzJEGSxCWO4',
    appId: '1:804667018998:ios:c517d75f22464b532226d7',
    messagingSenderId: '804667018998',
    projectId: 'khidma-2d423',
    storageBucket: 'khidma-2d423.firebasestorage.app',
    androidClientId: '804667018998-t3hrfdbepig7suftnqoqvqre6rs5uh0a.apps.googleusercontent.com',
    iosClientId: '804667018998-qh21lt7qgoljioiscf7eij7l7bum5kqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.khedma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz1pEt7Q4ZPWmecXBOlqpdarf-I8GPv5U',
    appId: '1:804667018998:web:05ae651f69f4c9342226d7',
    messagingSenderId: '804667018998',
    projectId: 'khidma-2d423',
    authDomain: 'khidma-2d423.firebaseapp.com',
    storageBucket: 'khidma-2d423.firebasestorage.app',
    measurementId: 'G-03X3PVBTGH',
  );
}
